### ISSUE TITLE
less compilation failed after installing v2.4 from bower

### ISSUE THREAD

**Issue by gauravdaxini** [almasaeed2010/AdminLTE#1665]
We have been using the admin-lte from quite long time. But, when we build our app last week and compiled the LESS file which depends on admin-lte LESS files, it failed.

ERROR
````
$ lessc assets/css/less/app.less assets/css/app.min.css --clean-css="--s1"
FileError: '../../../bower_components/bootstrap/less/mixins.less' wasn't found. Tried - {project_path}\assets\vendor\admin-lte\bower_components\bootstrap\less\mixins.less,{project_path}\bower_components\bootstrap\less\mixins.less,..\..\..\bower_components\bootstrap\less\mixins.less in {project_path}\assets\vendor\admin-lte\build\less\skins\skin-blue-light.less on line 5, column 1:
4  */
5 @import "../../../bower_components/bootstrap/less/mixins.less";
6 @import "../../../bower_components/bootstrap/less/variables.less";
````

Since bower installed the latest admin-lte(v2.4) which does not include the bower-components folder, when we compiled the LESS file it didn't get the bootstrap mixins and variables file from bower_components folder.

Please help to fix this.

**Comment by jake-harris** [comment]
I'm also getting this issue when installing via NPM.

**Comment by acacha** [comment]
Same problem here!

**Comment by vingrad** [comment]
same problem.

**Comment by vingrad** [comment]
> cd node_modules\admin-lte\
> bower install

**Comment by elboletaire** [comment]
Also, why the hell are all the bower_components packaged with the plugin? This is insane 😞

**Comment by elboletaire** [comment]
BTW, In my case I forced the version to be `2.3.11`.

**Comment by almasaeed2010** [comment]
Fixed in master by providing bootstrap less files in the build directory.

Thanks for reporting the issue!

**Comment by THETCR** [comment]
This issue should be opened again, since you missed line 11 & 12 in bootstrap-social.less and so the npm version still fails.  No less files from this projects should reference less files from the bower components. Especially not since the bootstrap less files are already in the build folder.

**Comment by gauravdaxini** [comment]
Thanks @almasaeed2010 for providing a quick fix. However, I'm still facing the issue.

You have forgotten to update the bootstrap less dependency PATH in skin's less file (some less file still contains `../../../bower_components/bootstrap/less/mixins.less` path which does not exist) which is causing the failure while compiling the less file.

Please help to fix this.

**Comment by LLNet** [comment]
Fix works fine for me.
```
from : ../../bower_components/bootstrap/less/mixins
if you have own in bower bootstrap: ../../../bootstrap/less/mixins
if not: ../bootstrap-less/mixins
```
same for variables

**Comment by ernestodgr** [comment]
the `npm run dev` command works well after doing what it says @vingrad, but now it happens that the menu does not work well
