### ISSUE TITLE
Box collapse does not work on an ajax loaded page.

### ISSUE THREAD

**Issue by Soullivaneuh** [almasaeed2010/AdminLTE#302]
If a page with AdminLTE boxes is loaded from ajax, the collapse system don't do anything.

The concerned code lines are here: https://github.com/almasaeed2010/AdminLTE/blob/master/dist/js/app.js#L365-L374

I think you sould use `.on('click')` function instead of `.click()` like I did on this workaround:

```coffee
o = $.AdminLTE.options;

$(o.boxWidgetOptions.boxWidgetSelectors.collapse).unbind 'click'
$(document).on 'click', o.boxWidgetOptions.boxWidgetSelectors.collapse, (e) ->
  e.preventDefault()
  $.AdminLTE.boxWidget.collapse $(@)

$(o.boxWidgetOptions.boxWidgetSelectors.remove).unbind 'click'
$(document).on 'click', o.boxWidgetOptions.boxWidgetSelectors.remove, (e) ->
  e.preventDefault()
  $.AdminLTE.boxWidget.remove $(@)
```

I will work on a PR if I have some time.

**Comment by almasaeed2010** [comment]
That's a great idea. I will review your PR and get back to you once I get a chance. 
Thank you!

**Comment by Soullivaneuh** [comment]
OK i'll get in touch. :+1:

**Comment by wch** [comment]
This would be really useful for my use case as well. I actually made exactly the same fix independently.

**Comment by kressly** [comment]
Yes click is deprecated in the newest version of jQuery. Now it is on('click') .

**Comment by almasaeed2010** [comment]
@kressly .click is not deprecated https://api.jquery.com/click/
However, it does not listen to click events on dynamically created elements which .on('click') does. Just a friendly correction.

**Comment by kressly** [comment]
Oh Ok thanks a lot. I was using jquery and was having an error and I read somewhere that click was deprecated and the solution was on('click'
Apparently I was not the only one 
http://stackoverflow.com/questions/11296530/jquery-onclick-vs-click-and-delegateclick

But thanks a lot for the correction bro

**Comment by Soullivaneuh** [comment]
Just a precision:

**Comment by Soullivaneuh** [comment]
Just a precision.document

```js
$('.some-class').on('click', function(e) {});
```

Will not work for dynamic elements.

```js
$(document).on('click', '.some-class', function(e) {});
$('#my-div').on('click', '.some-class', function(e) {});
```

Will work. I made this on my #304.

More info: http://stackoverflow.com/a/9344454/1731473

**Comment by funyx** [comment]
i suggest writing an ajax extend fn to reinit all plugins within the page on ajax call complete..

**Comment by almasaeed2010** [comment]
Fixed in v2.1.0

**Comment by peixinhu130** [comment]
Sorry for the English, but tested the 2.1.0 version and still does not work

**Comment by wch** [comment]
The fix in 3eb31be makes it so you need to call `.activateBox()` on a box after it's added. But instead of this:

```js
      $(_box).find(_this.selectors.collapse).on('click', function (e) {
        e.preventDefault();
        _this.collapse($(this));
      });
```

It would be simpler to do this, and not require calling `activateBox()` each time a box is added:

```js
      $(document).on('click', _this.selectors.collapse, function (e) {
        e.preventDefault();
        _this.collapse($(this));
      });
```

If `activateBox()` did other initialization besides attaching event handlers, it might make sense to keep it around, but it looks like it simply increases complexity right now. I can make a pull request if this sounds reasonable.

**Comment by matoho** [comment]
@wch, your proposed solution works very well for my heavily angular based app that basically loads everything dynamically. @almasaeed2010, how do you feel about implementing this in your main branch?
