### ISSUE TITLE
Right sidebar closing

### ISSUE THREAD

**Issue by lukacavic** [almasaeed2010/AdminLTE#408]
Hi, 

when I open right sidebar, it is showing...thats ok, but when changing tabs in sidebar it is closing immediatly..

**Comment by githubjeka** [comment]
Fixed in 2.1.1

**Comment by yufieko** [comment]
it's fixed, download the latest version 
[issues 405](https://github.com/almasaeed2010/AdminLTE/issues/405) , [adminLTE 2.1.1](https://github.com/almasaeed2010/AdminLTE/releases/tag/2.1.1)

**Comment by nicolas-besnard** [comment]
Still not working if [this is update-to-date](https://almsaeedstudio.com/themes/AdminLTE/index2.html)

**Comment by almasaeed2010** [comment]
@nicolas-besnard I updated the demo. 

Thank you.
