### ISSUE TITLE
SlimScroll with Fixed Layout when focus on mobile

### ISSUE THREAD

**Issue by SylvainSimon** [almasaeed2010/AdminLTE#427]
With mobile.
When fixed layout activated, slimscroll imported.

On focus on input in the sidebar (Issue reproductibility on your website also with the search input)
https://almsaeedstudio.com/themes/AdminLTE/index2.html

My project is create mobile website and my connection form is in the sidebar.

![2015-05-14_08-44-19](https://cloud.githubusercontent.com/assets/11244274/7627245/94f6fa4c-fa15-11e4-9d37-0c49a363169e.png)

When you focus an input in the sidebar, the keyboard appear, slimscroll is created by your event

      $(window, ".wrapper").resize(function () {
        _this.fix();
        _this.fixSidebar();
      });

scrollbar append and... keyboard close....

Tested in multiple android device with default browser (Chrome mobile)

**Comment by almasaeed2010** [comment]
I am not sure what the issue is. Could you please elaborate on the problem? What happens when the slimscroll is recreated?

**Comment by SylvainSimon** [comment]
I go to try explain you step by step.

- Go to your website on mobile (I'm on Android) (I have seen this bug on this). 
   It's important that the "fixed" option is activated.

- Look my screen in the referal post.

- When i touch an input text, the keyboard of android appear.
- When it's appear, he fire the slimscroll plugin to calculate size of sidebar and he delete scrollbar of the main content (Right)

- At the moment, i lose my focus on the input. 

3 solutions :
- If i double-touch on the input.
- If i desactive fixed option.
- If i desactive slimscroll menu.

But... i want to have fixed header AND slimscroll sidebar... It's complicated...

You understand ?
I'm french... sorry for my english x)

**Comment by almasaeed2010** [comment]
I tested on Samsung S4 and confirmed that the issue occurs on Chrome. I will try to fix it asap. Thank you for letting us know.

**Comment by SylvainSimon** [comment]
Solved ?

**Comment by almasaeed2010** [comment]
Please read https://github.com/almasaeed2010/AdminLTE/issues/1086

If you can test the issue to make sure it still exists, let me know and I'll reopen it.

**Comment by SylvainSimon** [comment]
The issue is always here. 
In fixed mode, open left sidebar, focus a field (Search field or other). 
Sidebar close automaticaly.

Tested in multiple android device with default browser (Chrome mobile)

**Comment by almasaeed2010** [comment]
Fixed in master. The next release will have the final update. 

Thanks for your patience!!

**Comment by Muhamann** [comment]
Hello,

i dont understand what you fixed here (in #427), because i see no difference to the old slimscroll.
The error is still there.
Android --> Chrome --> Slimcroll and fixed active --> Click on Input in Sidebar -> The Keyboard appears shortly and then disappears, so it cannot be used. 

I compares alpha2.4 with 2.3.11 .... its the same slimscroll.
Can you check this again please.

**Comment by Muhamann** [comment]
I see you made the Slimscroll Version "1.3.8" ?
But the error still exists... its not fixed...

**Comment by Muhamann** [comment]
Prusk Fix works:
https://github.com/almasaeed2010/AdminLTE/pull/1416/files
